# Generated by Django 2.1.2 on 2021-08-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('staus', models.CharField(blank=True, max_length=170, null=True)),
            ],
            options={
                'db_table': 'status_master',
            },
        ),
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=170, null=True)),
                ('address', models.CharField(blank=True, max_length=470, null=True)),
                ('lankmark', models.CharField(blank=True, max_length=270, null=True)),
                ('mobile_no', models.BigIntegerField(blank=True, null=True)),
                ('email_id', models.CharField(blank=True, max_length=270, null=True)),
                ('password', models.CharField(blank=True, max_length=270, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
