# Generated by Django 2.1.2 on 2021-08-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatogeryDetails',
            fields=[
                ('catogery_id', models.AutoField(primary_key=True, serialize=False)),
                ('catogery', models.CharField(blank=True, max_length=270, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catogery_details',
            },
        ),
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=370, null=True)),
                ('file_path', models.CharField(blank=True, max_length=670, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_details',
            },
        ),
        migrations.CreateModel(
            name='GroceryDetails',
            fields=[
                ('grocery_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=270, null=True)),
                ('brand', models.CharField(blank=True, max_length=270, null=True)),
                ('catogery_id', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('available_qty', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grocery_details',
            },
        ),
    ]
