# Generated by Django 2.1.2 on 2021-08-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catogerydetails',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
