# Generated by Django 2.1.2 on 2021-08-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210808_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocerydetails',
            old_name='grocery_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='grocerydetails',
            old_name='name',
            new_name='product_name',
        ),
    ]
